= Quotes and robots

[epigraph, Brian W. Kernighan, The Elements of Programming Style]
____
Debugging is twice as hard as writing the code in the first place.
Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.
____

Some interpret this classic quote from Kernighan, the K of K&R, as an instruction to write "dumb" code that doesn't use cognitively taxing abstractions.
Prefer simple code and constructs and you'll make maintaining it simpler and easier.

== How I interpret Kernighan's quote

When you write a program, you do so inside the circle of your knowledge and expertise. It is a product of everything you know, or think you know.
If you write the "clever" program, you approach the edge of your expertise. If you need to fix a bug in that program you may find that the
path to the solution leaves your circle. In order to find the fix, you have to expand the circle of your knowledge.

My interpretation is about cautiously pushing your boundaries. Cautiously, don't try to start an architectural revolution on a Friday afternoon by pushing some exotic pattern to prod. Do it in isolation, with benchmarks, tests, peer-review.

== Where do LLMs come into the picture?

If you think about it, using an LLM to produce code is parachuting well outside your circle. Most probably the only thing
you will be able to bring back to your circle of comfortable expertise is an intuition or rough understanding. You'll have a vague idea of how you can interact with the generated code well beyond the horizon

[.lead]
Use LLMs to expand your circle, not to get lost outside it. 
Use them to learn, to experiment, to short-circuit bad ideas. 
Grow your circle of knowledge.

