= On thinking transistors

Generative LLM models have three advantages compared to how humans transform information:

* faster consumption of input
* faster production of output
* larger context

The advantages become a subject of discourse when we introduce metrics like
quality, style, sustainability, serviceability, error rate, etc. Metrics that
we have no reliable and relevant ways to measure, mostly. This is the heart of
the AI debate. We anthropomorphised a tool, and measured its output like we
would a human's.

[.lead]
Human-like thinking mustn't be the goal.

I won't argue about the inherent nature of humans if there is one.
It doesn't matter if the aggregate output of the human intellect is positive or negative. I don't 
want machines, programs and LLMs to aim for human thinking. I don't want to come up with fake scenarios, change wording,
capitalize, rephrase and repeat instructions just to make a program do what I want.
We lie, scheme, play or participate in politics, ignore things because
of laziness, we are stubborn. This behavior has no place inside software. 

[.lead]
Natural language processing and output don't make the LLM
human. It doesn't make it think. It just makes it familiar.

And that's the 'killer-feature' of the LLM: familiarity. It doesn't have to be
correct, fast or transparent. It has to be familiar. An extension of
our human will. Not because of the inevitability of some
stubborn mathematical reason.

It has to be because that's the
direction LLMs went since 2022. That's our reality at the moment. We choose
the natural human language as our interface to the humongous black box that
generates more and more of our digital infrastructure.

I'd be much more interested in LLMs that generate
virtual machine code for an LLM VM, than in trying to modify the token output
distribution to generate syntactically and semantically correct code with LSPs,
MCPs, tools and... text files?

[.lead]
LLMs are fast token transformers of varying reliability that don't operate on the syntactic or
semantic level. Treat them as such.

I'd shake my head if someone on my team tried to write by their own hand every
piece of software they create. Googling, checking StackOverflow, copying, experimenting, using
preexisting solutions is part of the job. But verifying the source is the developer's responsibility.
I'm just as frustrated when I ask someone what this code does and they say "idk I copied it from StackOverflow"
as when the person says "idk AI wrote it". LLMs are just another source. One, we
can't cite as a single, universally uniform quality source, but produces of huge amount
of information.

I'd advise most people to use LLMs as what they are: consume a lot of
information fast, and produce information, keeping in mind the varying
correctness. If correctness isn't a concern, then don't think too much. If it
is, then it is your responsibility to verify your source. No amount of "AI agent
orchestrated swarm coding farm" bullshit can change that.
